swagger: '2.0'
info:
  title: Unite Society
  description: '**Work In Progress**<br/>**API Key** is the same as the API Endpoint'
  version: 0.0.1
  contact:
    name: VoraknoTech
    email: reachus@voraknotech.com
externalDocs:
  description: Documentation
  url: >-
    http://rebilly.github.io/ReDoc/?url=http://www.abhijit-kar.com/unite-society/swagger.yaml
host: chrome-setup-158308.appspot.com
basePath: /v1
tags:
  - name: Users
    description: Home for every query related to Users
schemes:
  - https
securityDefinitions:
  ApiKey:
    type: apiKey
    name: key
    in: query
security:
  - ApiKey: []
consumes:
  - application/json
produces:
  - application/json
x-servers:
  - url: custom-library-164415.appspot.com/v1
    description: Prod Server
  - url: custom-library-164415.appspot.com/v0
    description: Dev Server
paths:
  /users:
    get:
      tags:
        - Users
      deprecated: false
      summary: Get All, Just for Test
      description: Get All the Users
      operationId: get-all-users
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Users'
    post:
      tags:
        - Users
      summary: Create
      description: Maybe only Society Admin can create an User
      operationId: create-user
      parameters:
        - in: body
          name: body
          description: User Object
          required: true
          schema:
            $ref: '#/definitions/User'
      x-code-samples:
        - lang: KOTLIN
          source: >-
            Did you know that a Kotlin Client library can be generated using the
            Swagger Editor and that it would have all the type checks, limits
            and patterns specified here?
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/User'
          examples:
            application/json:
              id: CgsiCU5ldmVyTGFuZBIQCgVVc2VycxCAgICA2uOGCg
              firstname: John
              middlename: 'null'
              lastname: Doe
              email_ids:
                - john@example.com
              phone_numbers:
                - '9998887777'
              dob: '2018-01-26'
              role: MEMBER
              avatar_url: 'http://example.com/avatar.jpg'
              blood_group: A_POSITIVE
              society_id: ahVqfmNocm9tZS1zZXR1cC0xNTgzMDhyJwsSB1NvY2lldHkYgICAgICAgAkMCxIGRmFtaWx5GICAgICAgIAKDKIBCU5ldmVyTGFuZA
              family_id: ahVqfmNocm9tZS1zZXR1cC0xNTgzMDhyFAsSB1NvY2lldHkYgICAgICAgAkMogEJTmV2ZXJMYW5k
              date_created: '2018-01-26T13:26:53.557Z'
              date_updated: '2018-01-26T13:26:53.557Z'
              status: PENDING
  '/users/{id}/avatar':
    post:
      tags:
        - Users
      summary: Image
      description: Profile Image of the User
      operationId: upload-profile-image
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the User
          required: true
          type: string
        - name: file
          in: formData
          description: Profile Image
          required: true
          type: file
      x-code-samples:
        - lang: KOTLIN
          source: >-
            Did you know that a Kotlin Client library can be generated using the
            Swagger Editor and that it would have all the type checks, limits
            and patterns specified here?
      responses:
        '201':
          description: Uploaded
  '/users/{id}':
    get:
      tags:
        - Users
      summary: Read
      description: Only a user can get their whole user data
      operationId: get-user
      parameters:
        - name: id
          in: path
          description: The ID of the user that needs to be fetched
          required: true
          type: string
      x-code-samples:
        - lang: KOTLIN
          source: >-
            Did you know that a Kotlin Client library can be generated using the
            Swagger Editor and that it would have all the type checks, limits
            and patterns specified here?
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Bad Request
        '404':
          description: Not Found
    put:
      tags:
        - Users
      summary: Update
      description: Only the specific user can updated the data
      operationId: update-user
      parameters:
        - name: id
          in: path
          description: The ID of the user that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      x-code-samples:
        - lang: KOTLIN
          source: >-
            Did you know that a Kotlin Client library can be generated using the
            Swagger Editor and that it would have all the type checks, limits
            and patterns specified here?
      responses:
        '204':
          description: Updated
        '400':
          description: Bad Request
        '404':
          description: Not Found
    patch:
      tags:
        - Users
      summary: Patch
      description: Few targeted properties can be updated
      operationId: patch-user
      parameters:
        - name: id
          in: path
          description: The ID of the user that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      x-code-samples:
        - lang: KOTLIN
          source: >-
            Did you know that a Kotlin Client library can be generated using the
            Swagger Editor and that it would have all the type checks, limits
            and patterns specified here?
      responses:
        '204':
          description: Patched
        '400':
          description: Bad Request
        '404':
          description: Not Found
    delete:
      tags:
        - Users
      summary: Delete
      description: Only a Society Admin can delete the user
      operationId: delete-user
      parameters:
        - name: id
          in: path
          description: The ID of the user that needs to be deleted
          required: true
          type: string
      x-code-samples:
        - lang: KOTLIN
          source: >-
            Did you know that a Kotlin Client library can be generated using the
            Swagger Editor and that it would have all the type checks, limits
            and patterns specified here?
      responses:
        '204':
          description: Deleted
        '400':
          description: Bad Request
        '404':
          description: Not Found
definitions:
  Users:
    type: array
    items:
      $ref: '#/definitions/User'
  User:
    type: object
    required:
      - firstname
      - dob
      - society_id
      - family_id
      - date_created
      - date_updated
    properties:
      id:
        type: string
        readOnly: true
        description: ID can be used for further queries
      firstname:
        type: string
        description: First Name of the User
      middlename:
        type: string
        x-nullable: true
        description: Middle Name of the User
      lastname:
        type: string
        x-nullable: true
        description: Last Name of the User
      email_ids:
        type: array
        x-nullable: true
        items:
          type: string
          format: email
        description: Validated Email Ids
      phone_numbers:
        type: array
        x-nullable: true
        items:
          type: string
          pattern: '^\d{10}$'
          minLength: 10
          maxLength: 10
        description: 10 Digit Unformatted Phone Numbers
      dob:
        type: string
        format: date
        description: Date of Birth in UTC Zulu Format
      role:
        type: string
        description: Role of the User
        default: MEMBER
        enum:
          - OWNER
          - MEMBER
      avatar_url:
        type: string
        format: uri
        x-nullable: true
        description: User's Profile Photo
      blood_group:
        type: string
        description: Blood Group of the User
        default: A_POSITIVE
        enum:
          - O_NEGATIVE
          - O_POSITIVE
          - A_NEGATIVE
          - A_POSITIVE
          - B_NEGATIVE
          - B_POSITIVE
          - AB_NEGATIVE
          - AB_POSITIVE
      society_id:
        type: string
        description: ID of the Society the User belongs to
      family_id:
        type: string
        description: ID of the Family the User belongs to
      date_created:
        type: string
        format: date-time
        description: Date in UTC Zulu Format
      date_updated:
        type: string
        format: date-time
        description: Date in UTC Zulu Format
      status:
        type: string
        description: Status of the User's Account
        default: PENDING
        enum:
          - VERIFIED
          - PENDING
    example:
      firstname: John
      middlename: null
      lastname: Doe
      email_ids:
        - john@example.com
      phone_numbers:
        - '9998887777'
      dob: '2018-01-26'
      role: MEMBER
      avatar_url: 'http://example.com/avatar.jpg'
      blood_group: A_POSITIVE
      society_id: ahVqfmNocm9tZS1zZXR1cC0xNTgzMDhyJwsSB1NvY2lldHkYgICAgICAgAkMCxIGRmFtaWx5GICAgICAgIAKDKIBCU5ldmVyTGFuZA
      family_id: ahVqfmNocm9tZS1zZXR1cC0xNTgzMDhyFAsSB1NvY2lldHkYgICAgICAgAkMogEJTmV2ZXJMYW5k
      date_created: '2018-01-26T13:26:53.557Z'
      date_updated: '2018-01-26T13:26:53.557Z'
      status: PENDING
