swagger: '2.0'
info:
  description: '**Work In Progress**<br/>**API Key** is the same as the API Endpoint'
  version: 0.0.1
  title: Unite Society
  contact:
    name: VoraknoTech
    email: reachus@voraknotech.com
externalDocs:
  description: Beautiful Docs
  url: >-
    http://rebilly.github.io/ReDoc/?url=http://www.abhijit-kar.com/unite-society/swagger.yaml
host: custom-library-164415.appspot.com
basePath: /v1
tags:
  - name: Users
    description: Home for every query related to Users
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    post:
      tags:
        - Users
      summary: Create
      description: Maybe only Society Admin can create an User
      operationId: createUser
      parameters:
        - in: body
          name: body
          description: User Object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        default:
          description: Operation Successfull
  '/users/{username}':
    get:
      tags:
        - Users
      summary: Read
      description: ''
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          type: string
      responses:
        '200':
          description: Operation Successfull
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - Users
      summary: Update
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: name that need to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '400':
          description: Invalid user supplied
        '404':
          description: User not found
    delete:
      tags:
        - Users
      summary: Delete
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          type: string
      responses:
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    name: X-API-Key
    in: header
security:
  - ApiKeyAuth: []
definitions:
  User:
    type: object
    properties:
      id:
        type: string
        description: Id can be used for further queries
      firstName:
        type: string
        description: First Name of the User
      middleName:
        type: string
        description: Middle Name of the User
      lastName:
        type: string
        description: Last Name of the User
      email_ids:
        type: string
        description: Email Ids
      phone_numbers:
        type: string
        description: Unformatted Phone Number
      dob:
        type: string
        description: Date of Birth
      userStatus:
        type: integer
        format: int32
        description: User Status
    xml:
      name: User
