runtime: go
api_version: go1.8

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$
- specs
- gen
- LICENSE
- README.md
- .gitignore

handlers:
- url: /.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301
